name: Project Release - Deploy

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      #- name: Install Dependencies
      #  run: |
      #    python -m pip install --upgrade pip
      #    pip install -r requirements.txt -t ./
      #    chmod -R 755 .
      - name: Build Prod Archive
        run: zip doorapp.zip -r * .[^.]* -x '*.git*' -x 'lambda_test.py' --exclude=*.dist-info*
      - name: Deploy Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: doorFunction
          zip_file: doorapp.zip
      - name: Build Test Archive
        run: zip testapp.zip -r * .[^.]* -x '*.git*' -x 'lambda_function.py' --exclude=*.dist-info*
      - name: Deploy Test Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: test-doorFunction
          zip_file: testapp.zip
