name: Test Function - Build

on:
  push:
    paths:
      - 'lambda_test.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    #- name: Install Dependencies
    #  run: |
    #    python -m pip install --upgrade pip
    #    pip install -r requirements.txt -t ./
    #    chmod -R 755 .
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build Archive
      run: zip testapp.zip -r * .[^.]* -x '*.git*' -x 'lambda_function.py' --exclude=*.dist-info*
    - name: Deploy Test Lambda
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: test-doorFunction
        zip_file: testapp.zip
